/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package siprocafe;

/**
 *
 * @author USER
 */
public class frm_bloques extends javax.swing.JFrame {

    /**
     * Creates new form frm_bloques
     */
    public frm_bloques() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        texidelem_dot = new javax.swing.JTextField();
        texid_producto = new javax.swing.JTextField();
        texid_personal = new javax.swing.JTextField();
        jBguardar1 = new javax.swing.JButton();
        jBmodificar = new javax.swing.JButton();
        jBeliminar = new javax.swing.JButton();
        texfecdevo = new javax.swing.JTextField();
        texfecdevo1 = new javax.swing.JTextField();
        texid_personal1 = new javax.swing.JTextField();
        texfecdevo2 = new javax.swing.JTextField();
        texid_personal2 = new javax.swing.JTextField();
        texfecdevo3 = new javax.swing.JTextField();
        texid_personal3 = new javax.swing.JTextField();
        texfecdevo4 = new javax.swing.JTextField();
        texid_personal4 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jBeliminar1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSPelemdot = new javax.swing.JScrollPane();
        tbtotalpersonas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("Id_Analisis Suelo");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 18, -1, -1));

        texidelem_dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texidelem_dotActionPerformed(evt);
            }
        });
        jPanel2.add(texidelem_dot, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 13, 87, -1));

        texid_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texid_productoActionPerformed(evt);
            }
        });
        jPanel2.add(texid_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 42, 171, -1));

        texid_personal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texid_personalActionPerformed(evt);
            }
        });
        jPanel2.add(texid_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 71, 171, -1));

        jBguardar1.setBackground(new java.awt.Color(0, 153, 153));
        jBguardar1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBguardar1.setText("Guardar");
        jBguardar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBguardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardar1ActionPerformed(evt);
            }
        });
        jPanel2.add(jBguardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 252, -1, -1));

        jBmodificar.setBackground(new java.awt.Color(0, 153, 153));
        jBmodificar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBmodificar.setText("Modificar");
        jBmodificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmodificarActionPerformed(evt);
            }
        });
        jPanel2.add(jBmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 252, -1, -1));

        jBeliminar.setBackground(new java.awt.Color(0, 153, 153));
        jBeliminar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBeliminar.setText("Salir");
        jBeliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminarActionPerformed(evt);
            }
        });
        jPanel2.add(jBeliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 90, -1));

        texfecdevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texfecdevoActionPerformed(evt);
            }
        });
        jPanel2.add(texfecdevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 89, 124, -1));

        texfecdevo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texfecdevo1ActionPerformed(evt);
            }
        });
        jPanel2.add(texfecdevo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 54, 124, -1));

        texid_personal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texid_personal1ActionPerformed(evt);
            }
        });
        jPanel2.add(texid_personal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 106, 171, -1));

        texfecdevo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texfecdevo2ActionPerformed(evt);
            }
        });
        jPanel2.add(texfecdevo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 13, 124, -1));

        texid_personal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texid_personal2ActionPerformed(evt);
            }
        });
        jPanel2.add(texid_personal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 135, 171, -1));

        texfecdevo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texfecdevo3ActionPerformed(evt);
            }
        });
        jPanel2.add(texfecdevo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 147, 124, -1));

        texid_personal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texid_personal3ActionPerformed(evt);
            }
        });
        jPanel2.add(texid_personal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 164, 171, -1));

        texfecdevo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texfecdevo4ActionPerformed(evt);
            }
        });
        jPanel2.add(texfecdevo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 118, 124, -1));

        texid_personal4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texid_personal4ActionPerformed(evt);
            }
        });
        jPanel2.add(texid_personal4, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 199, 442, 40));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel26.setText("Fecha Muestra");
        jLabel26.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 47, -1, -1));

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel27.setText("Fecha Analisis");
        jLabel27.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 76, -1, -1));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel28.setText("Fecha Reporte");
        jLabel28.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 106, -1, -1));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel29.setText("Determinación");
        jLabel29.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 140, -1, -1));

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel30.setText("Resultado");
        jLabel30.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 169, -1, -1));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel31.setText("Recomendación");
        jLabel31.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 213, -1, -1));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel32.setText("Edad Cultivo");
        jLabel32.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 18, -1, -1));

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel33.setText("Id Producto");
        jLabel33.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 59, -1, -1));

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel34.setText("Id Personal");
        jLabel34.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 94, -1, -1));

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel35.setText("Metodo");
        jLabel35.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 123, -1, -1));

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel36.setText("Rango_Adeciado");
        jLabel36.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 152, -1, -1));

        jBeliminar1.setBackground(new java.awt.Color(0, 153, 153));
        jBeliminar1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBeliminar1.setText("Eliminar");
        jBeliminar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBeliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminar1ActionPerformed(evt);
            }
        });
        jPanel2.add(jBeliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 252, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bloques");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbtotalpersonas.setBackground(new java.awt.Color(153, 153, 153));
        tbtotalpersonas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabla Elementos de dotacion", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        tbtotalpersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jSPelemdot.setViewportView(tbtotalpersonas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSPelemdot)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSPelemdot, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texidelem_dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texidelem_dotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texidelem_dotActionPerformed

    private void texid_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texid_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texid_productoActionPerformed

    private void texid_personalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texid_personalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texid_personalActionPerformed

    private void jBguardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardar1ActionPerformed
        // TODO add your handling code here:
        //        Personal objetoPersonas = new Personal();
        //        objetoPersonas.InsertarPersonas(texid_producto, texid_personal, texid_personal,texid_personal);
        //        /*Actualiza los datos y muestra*/
        //        objetoPersonas.MostrarPersonas(tbtotalpersonas);
    }//GEN-LAST:event_jBguardar1ActionPerformed

    private void jBmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmodificarActionPerformed
        //        // TODO add your handling code here:
        //        Personal objetoPersonas=new Personal();
        //        objetoPersonas.ModificarPersonas(texid_personal, tbtotalpersonas, texid_producto, texid_personal, texid_personal, texid_personal);
        //        /*Actualiza los datos y muestra*/
        //        objetoPersonas.MostrarPersonas(tbtotalpersonas);

    }//GEN-LAST:event_jBmodificarActionPerformed

    private void jBeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminarActionPerformed
       frm_Menu_Principal_1 form =new frm_Menu_Principal_1();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBeliminarActionPerformed

    private void texfecdevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texfecdevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texfecdevoActionPerformed

    private void texfecdevo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texfecdevo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texfecdevo1ActionPerformed

    private void texid_personal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texid_personal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texid_personal1ActionPerformed

    private void texfecdevo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texfecdevo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texfecdevo2ActionPerformed

    private void texid_personal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texid_personal2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texid_personal2ActionPerformed

    private void texfecdevo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texfecdevo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texfecdevo3ActionPerformed

    private void texid_personal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texid_personal3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texid_personal3ActionPerformed

    private void texfecdevo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texfecdevo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texfecdevo4ActionPerformed

    private void texid_personal4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texid_personal4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texid_personal4ActionPerformed

    private void jBeliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBeliminar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_bloques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_bloques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_bloques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_bloques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_bloques().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBeliminar;
    private javax.swing.JButton jBeliminar1;
    private javax.swing.JButton jBguardar1;
    private javax.swing.JButton jBmodificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jSPelemdot;
    private javax.swing.JTable tbtotalpersonas;
    private javax.swing.JTextField texfecdevo;
    private javax.swing.JTextField texfecdevo1;
    private javax.swing.JTextField texfecdevo2;
    private javax.swing.JTextField texfecdevo3;
    private javax.swing.JTextField texfecdevo4;
    private javax.swing.JTextField texid_personal;
    private javax.swing.JTextField texid_personal1;
    private javax.swing.JTextField texid_personal2;
    private javax.swing.JTextField texid_personal3;
    private javax.swing.JTextField texid_personal4;
    private javax.swing.JTextField texid_producto;
    private javax.swing.JTextField texidelem_dot;
    // End of variables declaration//GEN-END:variables
}
