/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package siprocafe;

/**
 *
 * @author USER
 */
public class frm_eledotacion extends javax.swing.JFrame {

    /**
     * Creates new form frm_eledotacion
     */
    public frm_eledotacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        texidelem_dot = new javax.swing.JTextField();
        texfechpres = new javax.swing.JTextField();
        texfecdev = new javax.swing.JTextField();
        jBguardar1 = new javax.swing.JButton();
        jBmodificar = new javax.swing.JButton();
        jBeliminar = new javax.swing.JButton();
        jCBestadodevo = new javax.swing.JComboBox<>();
        txtidpers = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jCBClase = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        texnomele = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        texcant = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jCBestado1 = new javax.swing.JComboBox<>();
        jtsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Elementos de Dotación");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(638, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 40));

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("Id_Elementos de dotacion");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        texidelem_dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texidelem_dotActionPerformed(evt);
            }
        });
        jPanel2.add(texidelem_dot, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 14, 140, -1));

        texfechpres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texfechpresActionPerformed(evt);
            }
        });
        jPanel2.add(texfechpres, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 180, -1));

        texfecdev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texfecdevActionPerformed(evt);
            }
        });
        jPanel2.add(texfecdev, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 180, -1));

        jBguardar1.setBackground(new java.awt.Color(0, 153, 153));
        jBguardar1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jBguardar1.setText("Guardar");
        jBguardar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBguardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardar1ActionPerformed(evt);
            }
        });
        jPanel2.add(jBguardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        jBmodificar.setBackground(new java.awt.Color(0, 153, 153));
        jBmodificar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jBmodificar.setText("Modificar");
        jBmodificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmodificarActionPerformed(evt);
            }
        });
        jPanel2.add(jBmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        jBeliminar.setBackground(new java.awt.Color(0, 153, 153));
        jBeliminar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jBeliminar.setText("Eliminar");
        jBeliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminarActionPerformed(evt);
            }
        });
        jPanel2.add(jBeliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, -1));

        jCBestadodevo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entregado", "Devuelto ", "Debaja", " " }));
        jCBestadodevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBestadodevoActionPerformed(evt);
            }
        });
        jPanel2.add(jCBestadodevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, 135, -1));

        txtidpers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidpersActionPerformed(evt);
            }
        });
        jPanel2.add(txtidpers, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 130, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setText("Fecha prestamo");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("Fecha Devolución");
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("Estado devolucion ");
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, -1, -1));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setText("Id_personal");
        jLabel18.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 100, -1));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setText("Estado");
        jLabel19.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 61, -1));

        jCBClase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Devolutivo", "No devolutivo", " " }));
        jCBClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBClaseActionPerformed(evt);
            }
        });
        jPanel2.add(jCBClase, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 135, -1));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel21.setText("Nombre Elem Dot");
        jLabel21.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 160, -1));

        texnomele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texnomeleActionPerformed(evt);
            }
        });
        jPanel2.add(texnomele, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 171, -1));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel22.setText("Cantidad");
        jLabel22.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        texcant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texcantActionPerformed(evt);
            }
        });
        jPanel2.add(texcant, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 180, -1));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel23.setText("Clase");
        jLabel23.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 61, -1));

        jCBestado1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inctativo", " " }));
        jCBestado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBestado1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCBestado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 135, -1));

        jtsalir.setBackground(new java.awt.Color(0, 153, 153));
        jtsalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtsalir.setText("Salir");
        jtsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtsalirActionPerformed(evt);
            }
        });
        jPanel2.add(jtsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 82, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, 750, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texidelem_dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texidelem_dotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texidelem_dotActionPerformed

    private void texfechpresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texfechpresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texfechpresActionPerformed

    private void texfecdevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texfecdevActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texfecdevActionPerformed

    private void jBguardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardar1ActionPerformed
        // TODO add your handling code here:
        //        Elemento_dotacion objetoelemen_dota = new Elemento_dotacion();
        //        objetoelemen_dota.Insertarelemnetos(texidelem_dot, texnomele, texcant, texfechpres, texfecdev, txtidpers, jCBestadodevo, jCBClase, jCBestado1);
        //        /*Actualiza los datos y muestra*/
        //        objetoelemen_dota.Mostrarelementos(tbtotalpersonas);
    }//GEN-LAST:event_jBguardar1ActionPerformed

    private void jBmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmodificarActionPerformed
        // TODO add your handling code here:
        //        Elemento_dotacion objetoElemento_dotacion = new Elemento_dotacion();
        //        objetoElemento_dotacion.Modificarelementos(tbtotalpersonas, texidelem_dot, texfechpres, texfecdev, txtidpers, texnomele, texcant, jCBestadodevo, jCBClase, jCBestado1);
        //        /*Actualiza los datos y muestra*/
        //        objetoElemento_dotacion.Mostrarelementos(tbtotalpersonas);

    }//GEN-LAST:event_jBmodificarActionPerformed

    private void jBeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminarActionPerformed
        //        // TODO add your handling code here:
        //        Elemento_dotacion objetoElemento_dotacion = new Elemento_dotacion();
        //        objetoElemento_dotacion.EliminarElementos(texidelem_dot);
        //        /*Actualiza los datos y muestra*/
        //        objetoElemento_dotacion.Mostrarelementos(tbtotalpersonas);
    }//GEN-LAST:event_jBeliminarActionPerformed

    private void jCBestadodevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBestadodevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBestadodevoActionPerformed

    private void txtidpersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidpersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidpersActionPerformed

    private void jCBClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBClaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBClaseActionPerformed

    private void texnomeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texnomeleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texnomeleActionPerformed

    private void texcantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texcantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texcantActionPerformed

    private void jCBestado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBestado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBestado1ActionPerformed

    private void jtsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtsalirActionPerformed
        frm_Menu_Principal_1 form =new frm_Menu_Principal_1();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jtsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_eledotacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_eledotacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_eledotacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_eledotacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_eledotacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBeliminar;
    private javax.swing.JButton jBguardar1;
    private javax.swing.JButton jBmodificar;
    private javax.swing.JComboBox<String> jCBClase;
    private javax.swing.JComboBox<String> jCBestado1;
    private javax.swing.JComboBox<String> jCBestadodevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jtsalir;
    private javax.swing.JTextField texcant;
    private javax.swing.JTextField texfecdev;
    private javax.swing.JTextField texfechpres;
    private javax.swing.JTextField texidelem_dot;
    private javax.swing.JTextField texnomele;
    private javax.swing.JTextField txtidpers;
    // End of variables declaration//GEN-END:variables
}
