/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package siprocafe;

/**
 *
 * @author USER
 */
public class frm_analisis extends javax.swing.JFrame {

    /**
     * Creates new form frm_analisis
     */
    public frm_analisis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        texidanalsuel = new javax.swing.JTextField();
        texFechamuestra = new javax.swing.JTextField();
        texfechaanaliss = new javax.swing.JTextField();
        jBguardar1 = new javax.swing.JButton();
        jBmodificar = new javax.swing.JButton();
        jBeliminar = new javax.swing.JButton();
        texidbloque = new javax.swing.JTextField();
        texidproduct = new javax.swing.JTextField();
        texfecharep = new javax.swing.JTextField();
        texedadculti = new javax.swing.JTextField();
        Determi = new javax.swing.JTextField();
        textrangAdec = new javax.swing.JTextField();
        texresult = new javax.swing.JTextField();
        texmetodo = new javax.swing.JTextField();
        texrecomen = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jBeliminar1 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        texidpersonal1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSPelemdot = new javax.swing.JScrollPane();
        tbtotalpersonas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("Id_Analisis Suelo");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 18, -1, -1));

        texidanalsuel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texidanalsuelActionPerformed(evt);
            }
        });
        jPanel2.add(texidanalsuel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 87, -1));

        texFechamuestra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texFechamuestraActionPerformed(evt);
            }
        });
        jPanel2.add(texFechamuestra, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 171, -1));

        texfechaanaliss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texfechaanalissActionPerformed(evt);
            }
        });
        jPanel2.add(texfechaanaliss, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 171, -1));

        jBguardar1.setBackground(new java.awt.Color(0, 153, 153));
        jBguardar1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jBguardar1.setText("Guardar");
        jBguardar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBguardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardar1ActionPerformed(evt);
            }
        });
        jPanel2.add(jBguardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        jBmodificar.setBackground(new java.awt.Color(0, 153, 153));
        jBmodificar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jBmodificar.setText("Modificar");
        jBmodificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmodificarActionPerformed(evt);
            }
        });
        jPanel2.add(jBmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        jBeliminar.setBackground(new java.awt.Color(0, 153, 153));
        jBeliminar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jBeliminar.setText("Eliminar");
        jBeliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminarActionPerformed(evt);
            }
        });
        jPanel2.add(jBeliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, -1, -1));

        texidbloque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texidbloqueActionPerformed(evt);
            }
        });
        jPanel2.add(texidbloque, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 124, -1));

        texidproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texidproductActionPerformed(evt);
            }
        });
        jPanel2.add(texidproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 124, -1));

        texfecharep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texfecharepActionPerformed(evt);
            }
        });
        jPanel2.add(texfecharep, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 171, -1));

        texedadculti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texedadcultiActionPerformed(evt);
            }
        });
        jPanel2.add(texedadculti, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 124, -1));

        Determi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetermiActionPerformed(evt);
            }
        });
        jPanel2.add(Determi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 171, -1));

        textrangAdec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textrangAdecActionPerformed(evt);
            }
        });
        jPanel2.add(textrangAdec, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 124, -1));

        texresult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texresultActionPerformed(evt);
            }
        });
        jPanel2.add(texresult, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 171, -1));

        texmetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texmetodoActionPerformed(evt);
            }
        });
        jPanel2.add(texmetodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 124, -1));

        texrecomen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texrecomenActionPerformed(evt);
            }
        });
        jPanel2.add(texrecomen, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 460, 50));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel26.setText("Fecha Muestra");
        jLabel26.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 47, -1, -1));

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel27.setText("Fecha Analisis");
        jLabel27.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 76, -1, -1));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel28.setText("Fecha Reporte");
        jLabel28.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 106, -1, -1));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel29.setText("Determinación");
        jLabel29.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 140, -1, -1));

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel30.setText("Resultado");
        jLabel30.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 169, -1, -1));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel31.setText("Recomendación");
        jLabel31.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel32.setText("Edad Cultivo");
        jLabel32.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel33.setText("Id Producto");
        jLabel33.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel34.setText("Id bloque");
        jLabel34.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel35.setText("Metodo");
        jLabel35.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel36.setText("Rango_Adeciado");
        jLabel36.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, -1, -1));

        jBeliminar1.setBackground(new java.awt.Color(0, 153, 153));
        jBeliminar1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jBeliminar1.setText("Salir");
        jBeliminar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBeliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminar1ActionPerformed(evt);
            }
        });
        jPanel2.add(jBeliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 73, -1));

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel37.setText("Id Personal");
        jLabel37.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));

        texidpersonal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texidpersonal1ActionPerformed(evt);
            }
        });
        jPanel2.add(texidpersonal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 124, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 47, 630, 330));

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Analisis de Suelo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(373, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 50));

        tbtotalpersonas.setBackground(new java.awt.Color(153, 153, 153));
        tbtotalpersonas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabla Elementos de dotacion", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        tbtotalpersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jSPelemdot.setViewportView(tbtotalpersonas);

        getContentPane().add(jSPelemdot, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 379, 630, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texidanalsuelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texidanalsuelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texidanalsuelActionPerformed

    private void texFechamuestraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texFechamuestraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texFechamuestraActionPerformed

    private void texfechaanalissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texfechaanalissActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texfechaanalissActionPerformed

    private void jBguardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardar1ActionPerformed
         
        
                Analisis_suelo objetoanalisis = new Analisis_suelo();
                objetoanalisis.InsertarPersonas(texidanalsuel, texidbloque, texFechamuestra, texfechaanaliss, texfecharep, Determi, texresult, texrecomen, texedadculti, texidproduct, texidpersonal1, texmetodo, textrangAdec);
                /*Actualiza los datos y muestra*/
                objetoanalisis.MostrarPersonas(tbtotalpersonas);
                
    }//GEN-LAST:event_jBguardar1ActionPerformed

    private void jBmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmodificarActionPerformed
                // TODO add your handling code here:
                
                Analisis_suelo objetoanalisis = new Analisis_suelo();
                objetoanalisis.ModificarPersonas(texidanalsuel, texFechamuestra, texidbloque, texfechaanaliss, texfecharep, Determi, texresult, texrecomen, texedadculti, texidproduct, texidpersonal1, texmetodo, textrangAdec);
                /*Actualiza los datos y muestra*/
                objetoanalisis.MostrarPersonas(tbtotalpersonas);


    }//GEN-LAST:event_jBmodificarActionPerformed

    private void jBeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminarActionPerformed
                // TODO add your handling code here:
                
                Analisis_suelo objetoanalisis = new Analisis_suelo();
                objetoanalisis.EliminarPersonas(texidanalsuel);
                /*Actualiza los datos y muestra*/
                objetoanalisis.MostrarPersonas(tbtotalpersonas);

    }//GEN-LAST:event_jBeliminarActionPerformed

    private void texidbloqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texidbloqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texidbloqueActionPerformed

    private void texidproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texidproductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texidproductActionPerformed

    private void texfecharepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texfecharepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texfecharepActionPerformed

    private void texedadcultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texedadcultiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texedadcultiActionPerformed

    private void DetermiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetermiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DetermiActionPerformed

    private void textrangAdecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textrangAdecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textrangAdecActionPerformed

    private void texresultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texresultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texresultActionPerformed

    private void texmetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texmetodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texmetodoActionPerformed

    private void texrecomenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texrecomenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texrecomenActionPerformed

    private void jBeliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminar1ActionPerformed
        frm_Menu_Principal_1 form =new frm_Menu_Principal_1();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBeliminar1ActionPerformed

    private void texidpersonal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texidpersonal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texidpersonal1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_analisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_analisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_analisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_analisis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_analisis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Determi;
    private javax.swing.JButton jBeliminar;
    private javax.swing.JButton jBeliminar1;
    private javax.swing.JButton jBguardar1;
    private javax.swing.JButton jBmodificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jSPelemdot;
    private javax.swing.JTable tbtotalpersonas;
    private javax.swing.JTextField texFechamuestra;
    private javax.swing.JTextField texedadculti;
    private javax.swing.JTextField texfechaanaliss;
    private javax.swing.JTextField texfecharep;
    private javax.swing.JTextField texidanalsuel;
    private javax.swing.JTextField texidbloque;
    private javax.swing.JTextField texidpersonal1;
    private javax.swing.JTextField texidproduct;
    private javax.swing.JTextField texmetodo;
    private javax.swing.JTextField texrecomen;
    private javax.swing.JTextField texresult;
    private javax.swing.JTextField textrangAdec;
    // End of variables declaration//GEN-END:variables
}
