/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package siprocafe;

/**
 *
 * @author USER
 */
public class frm_producto extends javax.swing.JFrame {

    /**
     * Creates new form frm_producto
     */
    public frm_producto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        texidproducto = new javax.swing.JTextField();
        texitipo = new javax.swing.JTextField();
        texnombre = new javax.swing.JTextField();
        jBguardar1 = new javax.swing.JButton();
        jBmodificar = new javax.swing.JButton();
        texfecha_de_recoleccion = new javax.swing.JTextField();
        texfecha_de_ingreso = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        textiempo_inicial_lavado = new javax.swing.JTextField();
        texfecha_de_lavado = new javax.swing.JTextField();
        texcantidad = new javax.swing.JTextField();
        textiempo_final_lavado = new javax.swing.JTextField();
        texnumero_secadero = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        texnumero_secadero1 = new javax.swing.JTextField();
        texnumero_secadero2 = new javax.swing.JTextField();
        texnumero_secadero3 = new javax.swing.JTextField();
        texnumero_secadero4 = new javax.swing.JTextField();
        jBeliminar1 = new javax.swing.JButton();
        jtsalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSPelemdot = new javax.swing.JScrollPane();
        tbtotalpersonas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("Id_producto");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 18, -1, -1));

        texidproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texidproductoActionPerformed(evt);
            }
        });
        jPanel2.add(texidproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 170, -1));

        texitipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texitipoActionPerformed(evt);
            }
        });
        jPanel2.add(texitipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 171, -1));

        texnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texnombreActionPerformed(evt);
            }
        });
        jPanel2.add(texnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 171, -1));

        jBguardar1.setBackground(new java.awt.Color(0, 153, 153));
        jBguardar1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jBguardar1.setText("Guardar");
        jBguardar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBguardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardar1ActionPerformed(evt);
            }
        });
        jPanel2.add(jBguardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        jBmodificar.setBackground(new java.awt.Color(0, 153, 153));
        jBmodificar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jBmodificar.setText("Modificar");
        jBmodificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmodificarActionPerformed(evt);
            }
        });
        jPanel2.add(jBmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        texfecha_de_recoleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texfecha_de_recoleccionActionPerformed(evt);
            }
        });
        jPanel2.add(texfecha_de_recoleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 87, -1));
        jPanel2.add(texfecha_de_ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 87, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setText("tipo");
        jLabel15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 58, -1, -1));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("Nombre");
        jLabel16.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 87, -1, -1));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("Fecha de ingreso");
        jLabel17.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 122, -1, -1));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setText("Fecha de recolección");
        jLabel18.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 157, -1, -1));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setText("tiempo final lavado");
        jLabel19.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setText("Cantidad");
        jLabel20.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel21.setText("Tiempo inicial lavado");
        jLabel21.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 215, -1, -1));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel22.setText("Fecha de lavado");
        jLabel22.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 186, -1, -1));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel23.setText("Numero secadero");
        jLabel23.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        textiempo_inicial_lavado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textiempo_inicial_lavadoActionPerformed(evt);
            }
        });
        jPanel2.add(textiempo_inicial_lavado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 87, -1));

        texfecha_de_lavado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texfecha_de_lavadoActionPerformed(evt);
            }
        });
        jPanel2.add(texfecha_de_lavado, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 87, -1));

        texcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texcantidadActionPerformed(evt);
            }
        });
        jPanel2.add(texcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 171, -1));

        textiempo_final_lavado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textiempo_final_lavadoActionPerformed(evt);
            }
        });
        jPanel2.add(textiempo_final_lavado, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 171, -1));

        texnumero_secadero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texnumero_secaderoActionPerformed(evt);
            }
        });
        jPanel2.add(texnumero_secadero, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 171, -1));

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel24.setText("Clasificaciòn");
        jLabel24.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, -1, -1));

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel25.setText("Orden Venta");
        jLabel25.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, -1));

        jLabel26.setBackground(new java.awt.Color(255, 255, 255));
        jLabel26.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel26.setText("Id_Factura");
        jLabel26.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, -1, 20));

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel27.setText("Id_Personal");
        jLabel27.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, -1));

        texnumero_secadero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texnumero_secadero1ActionPerformed(evt);
            }
        });
        jPanel2.add(texnumero_secadero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 171, -1));

        texnumero_secadero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texnumero_secadero2ActionPerformed(evt);
            }
        });
        jPanel2.add(texnumero_secadero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 171, -1));

        texnumero_secadero3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texnumero_secadero3ActionPerformed(evt);
            }
        });
        jPanel2.add(texnumero_secadero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 171, -1));

        texnumero_secadero4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texnumero_secadero4ActionPerformed(evt);
            }
        });
        jPanel2.add(texnumero_secadero4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 171, -1));

        jBeliminar1.setBackground(new java.awt.Color(0, 153, 153));
        jBeliminar1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jBeliminar1.setText("Eliminar");
        jBeliminar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBeliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminar1ActionPerformed(evt);
            }
        });
        jPanel2.add(jBeliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 60, -1));

        jtsalir.setBackground(new java.awt.Color(0, 153, 153));
        jtsalir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jtsalir.setText("Salir");
        jtsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtsalirActionPerformed(evt);
            }
        });
        jPanel2.add(jtsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 82, 30));

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Productos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbtotalpersonas.setBackground(new java.awt.Color(153, 153, 153));
        tbtotalpersonas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabla Elementos de dotacion", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        tbtotalpersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jSPelemdot.setViewportView(tbtotalpersonas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addComponent(jSPelemdot)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSPelemdot, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texidproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texidproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texidproductoActionPerformed

    private void texitipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texitipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texitipoActionPerformed

    private void texnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texnombreActionPerformed

    private void jBguardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardar1ActionPerformed
        // TODO add your handling code here:
        //        Producto1 objetoProducto = new Producto1();
        //        objetoProducto.InsertarProducto(texidproducto, texitipo, texnombre, texfecha_de_ingreso, texfecha_de_recoleccion, texfecha_de_lavado, textiempo_inicial_lavado, texid_factura, textiempo_final_lavado, texcantidad, texnumero_secadero, texclasificacion, texorden_venta, texid_personal);
        //        /*Actualiza los datos y muestra*/
        //        objetoProducto.MostrarProducto(tbtotalpersonas);
    }//GEN-LAST:event_jBguardar1ActionPerformed

    private void jBmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmodificarActionPerformed
        //        // TODO add your handling code here:
        //        Producto1 objetoProducto1=new Producto1();
        //        objetoProducto1.ModificarProduto(texidproducto, texitipo, texnombre, texfecha_de_ingreso, texfecha_de_recoleccion, texfecha_de_lavado, textiempo_inicial_lavado, texid_factura, textiempo_final_lavado, texcantidad, texnumero_secadero, texclasificacion, texorden_venta, texid_personal);
        //        /*Actualiza los datos y muestra*/
        //        objetoProducto1.MostrarProducto(tbtotalpersonas);

    }//GEN-LAST:event_jBmodificarActionPerformed

    private void texfecha_de_recoleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texfecha_de_recoleccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texfecha_de_recoleccionActionPerformed

    private void textiempo_inicial_lavadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textiempo_inicial_lavadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textiempo_inicial_lavadoActionPerformed

    private void texfecha_de_lavadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texfecha_de_lavadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texfecha_de_lavadoActionPerformed

    private void texcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texcantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texcantidadActionPerformed

    private void textiempo_final_lavadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textiempo_final_lavadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textiempo_final_lavadoActionPerformed

    private void texnumero_secaderoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texnumero_secaderoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texnumero_secaderoActionPerformed

    private void jtsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtsalirActionPerformed
   frm_Menu_Principal_1 form =new frm_Menu_Principal_1();
        form.setVisible(true);
        this.setVisible(false);
      
    }//GEN-LAST:event_jtsalirActionPerformed

    private void texnumero_secadero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texnumero_secadero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texnumero_secadero1ActionPerformed

    private void texnumero_secadero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texnumero_secadero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texnumero_secadero2ActionPerformed

    private void texnumero_secadero3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texnumero_secadero3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texnumero_secadero3ActionPerformed

    private void texnumero_secadero4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texnumero_secadero4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texnumero_secadero4ActionPerformed

    private void jBeliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBeliminar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBeliminar1;
    private javax.swing.JButton jBguardar1;
    private javax.swing.JButton jBmodificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jSPelemdot;
    private javax.swing.JButton jtsalir;
    private javax.swing.JTable tbtotalpersonas;
    private javax.swing.JTextField texcantidad;
    private javax.swing.JTextField texfecha_de_ingreso;
    private javax.swing.JTextField texfecha_de_lavado;
    private javax.swing.JTextField texfecha_de_recoleccion;
    private javax.swing.JTextField texidproducto;
    private javax.swing.JTextField texitipo;
    private javax.swing.JTextField texnombre;
    private javax.swing.JTextField texnumero_secadero;
    private javax.swing.JTextField texnumero_secadero1;
    private javax.swing.JTextField texnumero_secadero2;
    private javax.swing.JTextField texnumero_secadero3;
    private javax.swing.JTextField texnumero_secadero4;
    private javax.swing.JTextField textiempo_final_lavado;
    private javax.swing.JTextField textiempo_inicial_lavado;
    // End of variables declaration//GEN-END:variables
}
