/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package siprocafe;

/**
 *
 * @author USER
 */
public class frm_Ordenfactura extends javax.swing.JFrame {

    /**
     * Creates new form frm_Ordenfactura
     */
    public frm_Ordenfactura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbtotalpersonas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jL = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        texidfact = new javax.swing.JTextField();
        texFecha_elab = new javax.swing.JTextField();
        texFecha_pago = new javax.swing.JTextField();
        texid_personal = new javax.swing.JTextField();
        texcliente = new javax.swing.JTextField();
        texidproducto = new javax.swing.JTextField();
        texvalor_total = new javax.swing.JTextField();
        texForma_pago = new javax.swing.JTextField();
        jBguardar1 = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        jBeliminar = new javax.swing.JButton();
        Texvalor_unit = new javax.swing.JTextField();
        Texcantidad = new javax.swing.JTextField();
        TexDescripcion = new javax.swing.JTextField();
        jBmodificar1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbtotalpersonas.setBackground(new java.awt.Color(204, 204, 255));
        tbtotalpersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tbtotalpersonas);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 730, 150));

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Fecha Elaboracion");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Cliente");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 46, 80, 16));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Id_Producto");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 81, -1, -1));

        jL.setBackground(new java.awt.Color(255, 255, 255));
        jL.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jL.setText("cantidad");
        jPanel2.add(jL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, 24));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("descripcions");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, 24));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Valor unidad");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 24));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("Id_Factura ");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 18, 90, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setText("Fecha de Pago");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("Valor Total");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 90, -1));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("Forma de Pago");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, -1));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setText("Vendedor");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, -1, -1));

        texidfact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texidfactActionPerformed(evt);
            }
        });
        jPanel2.add(texidfact, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 87, -1));

        texFecha_elab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texFecha_elabActionPerformed(evt);
            }
        });
        jPanel2.add(texFecha_elab, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 163, -1));

        texFecha_pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texFecha_pagoActionPerformed(evt);
            }
        });
        jPanel2.add(texFecha_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 163, -1));

        texid_personal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texid_personalActionPerformed(evt);
            }
        });
        jPanel2.add(texid_personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, 163, -1));

        texcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texclienteActionPerformed(evt);
            }
        });
        jPanel2.add(texcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 142, -1));

        texidproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texidproductoActionPerformed(evt);
            }
        });
        jPanel2.add(texidproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 171, -1));

        texvalor_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texvalor_totalActionPerformed(evt);
            }
        });
        jPanel2.add(texvalor_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 163, -1));

        texForma_pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texForma_pagoActionPerformed(evt);
            }
        });
        jPanel2.add(texForma_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 163, -1));

        jBguardar1.setBackground(new java.awt.Color(204, 204, 204));
        jBguardar1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jBguardar1.setText("Guardar");
        jBguardar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBguardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardar1ActionPerformed(evt);
            }
        });
        jPanel2.add(jBguardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

        Salir.setBackground(new java.awt.Color(204, 204, 204));
        Salir.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        Salir.setText("Salir");
        Salir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jPanel2.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 65, -1));

        jBeliminar.setBackground(new java.awt.Color(204, 204, 204));
        jBeliminar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jBeliminar.setText("Eliminar");
        jBeliminar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminarActionPerformed(evt);
            }
        });
        jPanel2.add(jBeliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));
        jPanel2.add(Texvalor_unit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 171, -1));

        Texcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TexcantidadActionPerformed(evt);
            }
        });
        jPanel2.add(Texcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 171, -1));
        jPanel2.add(TexDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 277, 44));

        jBmodificar1.setBackground(new java.awt.Color(204, 204, 204));
        jBmodificar1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jBmodificar1.setText("Modificar");
        jBmodificar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBmodificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmodificar1ActionPerformed(evt);
            }
        });
        jPanel2.add(jBmodificar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 730, 320));

        jPanel3.setBackground(new java.awt.Color(0, 102, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Facturación");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 237, 44));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 54));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBmodificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmodificar1ActionPerformed
        // TODO add your handling code here:
        //        Personal objetoPersonas=new Personal();
        //        objetoPersonas.MostrarPersonas(tbtotalpersonas);
        //        objetoPersonas.ModificarPersonas(texcliente, texidfact, texidproducto, Texcantidad, Texvalor_unit, TexDescripcion, texFecha_elab, texFecha_pago, texvalor_total, texForma_pago, texid_personal, jComboBoxestado);
        //        /*Actualiza los datos y muestra*/
        //        objetoPersonas.MostrarPersonas(tbtotalpersonas);
    }//GEN-LAST:event_jBmodificar1ActionPerformed

    private void TexcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TexcantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TexcantidadActionPerformed

    private void jBeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminarActionPerformed
        // TODO add your handling code here:
        //        Personal objetoPersonas=new Personal();
        //        objetoPersonas.EliminarPersonas(texidfact);
        //        /*Actualiza los datos y muestra*/
        //        objetoPersonas.MostrarPersonas(tbtotalpersonas);
    }//GEN-LAST:event_jBeliminarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed

        frm_Menu_Principal_1 form =new frm_Menu_Principal_1();
        form.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SalirActionPerformed

    private void jBguardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardar1ActionPerformed
        // TODO add your handling code here:
        //        Personal objetoPersonas = new Personal();
        //        objetoPersonas.InsertarPersonas(texidfact,texcliente, texidproducto, Texcantidad, Texvalor_unit, TexDescripcion, texFecha_elab, texFecha_pago, texvalor_total, texForma_pago, texid_personal, jComboBoxestado);

        /*Actualiza los datos y muestra*/
        //
        //        objetoPersonas.MostrarPersonas(tbtotalpersonas);
    }//GEN-LAST:event_jBguardar1ActionPerformed

    private void texForma_pagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texForma_pagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texForma_pagoActionPerformed

    private void texvalor_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texvalor_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texvalor_totalActionPerformed

    private void texidproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texidproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texidproductoActionPerformed

    private void texclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texclienteActionPerformed

    private void texid_personalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texid_personalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texid_personalActionPerformed

    private void texFecha_pagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texFecha_pagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texFecha_pagoActionPerformed

    private void texFecha_elabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texFecha_elabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texFecha_elabActionPerformed

    private void texidfactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texidfactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texidfactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Ordenfactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Ordenfactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Ordenfactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Ordenfactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Ordenfactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Salir;
    private javax.swing.JTextField TexDescripcion;
    private javax.swing.JTextField Texcantidad;
    private javax.swing.JTextField Texvalor_unit;
    private javax.swing.JButton jBeliminar;
    private javax.swing.JButton jBguardar1;
    private javax.swing.JButton jBmodificar1;
    private javax.swing.JLabel jL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbtotalpersonas;
    private javax.swing.JTextField texFecha_elab;
    private javax.swing.JTextField texFecha_pago;
    private javax.swing.JTextField texForma_pago;
    private javax.swing.JTextField texcliente;
    private javax.swing.JTextField texid_personal;
    private javax.swing.JTextField texidfact;
    private javax.swing.JTextField texidproducto;
    private javax.swing.JTextField texvalor_total;
    // End of variables declaration//GEN-END:variables
}
