/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package siprocafe;

/**
 *
 * @author Karen Yency Pinedo
 */
public class Principal_menu extends javax.swing.JFrame {

    /**
     * Creates new form Principal_menu
     */
    public Principal_menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDpescritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        personal = new javax.swing.JButton();
        personal1 = new javax.swing.JButton();
        personal2 = new javax.swing.JButton();
        personal3 = new javax.swing.JButton();
        personal4 = new javax.swing.JButton();
        personal5 = new javax.swing.JButton();
        personal6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDpescritorio.setBackground(new java.awt.Color(47, 206, 47));
        jDpescritorio.setForeground(java.awt.SystemColor.activeCaptionBorder);
        jDpescritorio.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        jDpescritorio.setName("MENU PRINCIPAL"); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logocc.jpg"))); // NOI18N
        jLabel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);

        personal.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        personal.setText("Analisis de -Suelo");

        personal1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        personal1.setText("Factura");

        personal2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        personal2.setText("Cliente");
        personal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personal2ActionPerformed(evt);
            }
        });

        personal3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        personal3.setText("Personal");

        personal4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        personal4.setText("Producto");
        personal4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personal4ActionPerformed(evt);
            }
        });

        personal5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        personal5.setText("Bloque");

        personal6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        personal6.setText("Elemento de -dotación");

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));

        jLabel2.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Menú Principal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDpescritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDpescritorio.setLayer(personal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDpescritorio.setLayer(personal1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDpescritorio.setLayer(personal2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDpescritorio.setLayer(personal3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDpescritorio.setLayer(personal4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDpescritorio.setLayer(personal5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDpescritorio.setLayer(personal6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDpescritorio.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDpescritorioLayout = new javax.swing.GroupLayout(jDpescritorio);
        jDpescritorio.setLayout(jDpescritorioLayout);
        jDpescritorioLayout.setHorizontalGroup(
            jDpescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDpescritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(personal3)
                .addGap(31, 31, 31)
                .addComponent(personal4)
                .addGap(27, 27, 27)
                .addComponent(personal6)
                .addGap(32, 32, 32)
                .addComponent(personal2)
                .addGap(34, 34, 34)
                .addComponent(personal5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(personal)
                .addGap(35, 35, 35)
                .addComponent(personal1)
                .addGap(21, 21, 21))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDpescritorioLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDpescritorioLayout.setVerticalGroup(
            jDpescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDpescritorioLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(jDpescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(personal3)
                    .addComponent(personal4)
                    .addComponent(personal6)
                    .addComponent(personal2)
                    .addComponent(personal5)
                    .addComponent(personal)
                    .addComponent(personal1))
                .addGap(71, 71, 71)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDpescritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDpescritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personal4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personal4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personal4ActionPerformed

    private void personal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personal2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personal2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDpescritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton personal;
    private javax.swing.JButton personal1;
    private javax.swing.JButton personal2;
    private javax.swing.JButton personal3;
    private javax.swing.JButton personal4;
    private javax.swing.JButton personal5;
    private javax.swing.JButton personal6;
    // End of variables declaration//GEN-END:variables
}
